title: Satellite
header: Satellite
author: Michal Muransky
email: mike.muransky@gmail.com
description: Change is the essential process of all existence.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: michal-muranský-02a56144
github_username: monolithprojects
permalink: /posts/:year-:month-:day-:title
social-network-links:
  email: "mike.muransky@gmail.com"
  facebook: 
  github: monolithprojects
#  reddit: yourname
  linkedin: michal-muransky-02a56144
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  youtube: user/deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname

# google_analytics:

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from