title: Satellite
header: Satellite
author: Michal Muransky
email: mike.muransky@gmail.com
description: Change is the essential process of all existence.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: michal-muranský-02a56144
github_username: monolithprojects
permalink: /posts/:year-:month-:day-:title
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: monolithprojects
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: MonolithSVK
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

# google_analytics:

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from