baseURL: https://monolithprojects.github.io

languageCode: en-us
title: "Satellite"
theme: "toha"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1

# Control TOC depth
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

outputs:
  home:
    - HTML
    - RSS
    - JSON

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  background: /images/site/background.jpg
  # GitHub repo URL of your site
  gitRepo: https://github.com/monolithprojects/monolithprojects.github.io
  # Default branch of your Git repo
  gitBranch: source

  # specify whether you want to write some blog posts or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: true

  features:
    # Enable and configure portfolio
    portfolio:
      enable: true
    # Enable and configure blog posts
    blog:
      enable: true
      # Share post on different social media
      shareButtons:
        facebook: true
        twitter: true
        linkedin: true
        reddit: true
        whatsapp: true
        email: true
        # tumblr: true
        # pocket: true
        # diaspora: true
        # mastodon: true

    # Enable & configure "Notes" features
    notes:
      enable: true

    # Enable comment feature. There, should be only one of them.
    comment:
      enable: false
      disqus:
        shortName: toha-example-site
      # valine:
      #   appId: HTV6askWxVo3vOxlqjjaq2hd-MsYXbMMI
      #   appKey: pVrT3C85KGIuk27t07eh6bUC
      #   avatar: retro
      #   placeholder: Share your thought.
      #   lang: en
      #   recordIP: true
      #   enableQQ: true
      # utteranc:
      #   repo: github.com/hugo-toha/hugo-toha.github.io
      #   issueTerm: title
      #   theme: github-light

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Show tags under the post title
  enableTags: true

  # If you want to use different country flag for a language, specify them here.
  # flagOverwrites:
  # - languageCode: en
  #   countryCode: us

  # Provide footer configuration.
  footer:
    enable: true
    # You can provide your custom footer template using this option.
    # Put your template in "layouts/partials" folder of your repo.
    template: footer.html
    # Show/hide navigation in the footer. Default is "true".
    navigation:
      enable: true
    # Show/hide "Contact Me" section in the footer. Default is "true".
    contactMe:
      enable: true
    # Show/hide credentials section in the footer. Default is "true".
    credentials:
      enable: true

    # Show/hide newsletter section in the footer. Default is "true".
    # Currently, it supports "mailchimp".
    newsletter:
      enable: false
      # provider: mailchimp
      # mailchimpURL: https://github.us1.list-manage.com/subscribe/post?u=19de52a4603135aae97163fd8&amp;id=094a24c76e

    # Show/hide disclaimer notice in the footer. Default is "false".
    disclaimer:
      enable: true
